pulse :
  pulse_duration : 100
  DT : 50
  Omega_max : .5
  delta : 0.
  pulse_type : const
MPS_config:
  max_bond_dim: 2048
  extra_krylov_tolerance: !!float 1
  num_gpus_to_use: 2
  precision: !!float 1e-8
SV_config:
  max_krylov_dim : 100
  krylov_tolerance : !!float 1e-12
